### ISSUE TITLE
Enhance README

### ISSUE THREAD

**Issue by ChristopherRabotin** [Sparrho/bungiesearch#101]
Should add information about the new features done by @afrancis13:
+ Bulk delete
+ `prepare{}` field
+ Templates

Also check documentation for typos.

**Comment by ChristopherRabotin** [comment]
Also update travis: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade .

**Comment by ChristopherRabotin** [comment]
The README in RST version was kinda done quickly and wasn't thoroughly checked: there is some remaining markdown syntax which must be fixed.

**Comment by NullSoldier** [comment]
I think that we're already using containers in travis because it won't let me use sudo. I think they migrated us over automatically. The container also starts in seconds, but if you require sudo it takes awhile.

**Comment by ChristopherRabotin** [comment]
Yes, that's correct, we are using containers on Travis. I had to do a minor change in the .travis file.
