### ISSUE TITLE
Release with no README?

### ISSUE THREAD

**Issue by afrancis13** [Sparrho/bungiesearch#105]
When I download the new release of bungiesearch, this happens:
```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/yp/ddctgj6s3vv0wgkm57b2w4040000gn/T/pip-build-pR13wb/bungiesearch/setup.py", line 11, in <module>
        with open(join(dirname(__file__), 'README.md')) as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/yp/ddctgj6s3vv0wgkm57b2w4040000gn/T/pip-build-pR13wb/bungiesearch/README.md'
```
I downloaded the compressed folder, opened it up, and, indeed, the README has disappeared. Do you have any idea why this may have happened?

**Comment by ChristopherRabotin** [comment]
Hum, no I don't know how that could have happened. I'll have to check that in like twelve hours, sorry.

**Comment by ChristopherRabotin** [comment]
Thanks for finding that. Please use [version 1.2.1](https://github.com/Sparrho/bungiesearch/releases/tag/v1.2.1) instead. It's already on Pypi too.
