### ISSUE TITLE
Add dependency for elasticsearch<=1.7.0 or update bungiesearch for compatibility with newer versions

### ISSUE THREAD

**Issue by marcinn** [Sparrho/bungiesearch#114]
`elasticsearch>1.7.0` does not provide `helpers.bulk_index()` method, which was deprecated.

Installation of `bungiesearch` resolves dependencies for `elasticsearch-dsl==0.0.9` and then `elasticsearch==2.1.0`, which is incompatible with `bungiesearch==1.2.1` and causes an `ImportError`:

```
  File "/home/marcin/src/projekty/xxx/eggs/bungiesearch-1.2.1-py2.7.egg/bungiesearch/managers.py", line 36, in contribute_to_class
    from .signals import get_signal_processor
  File "/home/marcin/src/projekty/xxx/eggs/bungiesearch-1.2.1-py2.7.egg/bungiesearch/signals.py", line 7, in <module>
    from .utils import update_index, delete_index_item
  File "/home/marcin/src/projekty/xxx/eggs/bungiesearch-1.2.1-py2.7.egg/bungiesearch/utils.py", line 6, in <module>
    from elasticsearch.helpers import bulk_index
ImportError: cannot import name bulk_index
```

Bungieshearch `setup.py` should include dependency for `elasticsearch<=1.7.0` or provide compatibility for newer versions.

**Comment by ChristopherRabotin** [comment]
Thanks for the bug report. I think that would be correct with https://github.com/Sparrho/bungiesearch/pull/113, correct?

I hope to work on this in the next 48 hours.

**Comment by marcinn** [comment]
Yes, it should work. :+1: 
I didn't saw #113 before, sorry for duplicate.  Waiting for pypi bugfix release :) Thanks!

**Comment by ChristopherRabotin** [comment]
@marcinn , version 1.2.2 has been released on pypi.

**Comment by marcinn** [comment]
thanks!
