### ISSUE TITLE
Issue if multiple search indexes defined for the same model

### ISSUE THREAD

**Issue by Folcon** [Sparrho/bungiesearch#64]
If multiple search indexes defined for the same model, it arbitrarily picks one.

Present workaround requires creating an alias which explicitly sets the `self.search_instance._index` before returning the `self.search_instance`.

**Comment by ChristopherRabotin** [comment]
+ [ ] Allow ModelIndex instance to be marked as default. Multiple defaults should fail on initialization.
+ [ ] Add a `post_save` boolean returning function to check whether this content should be saved on the given index via this ModelIndex: allows for multiple indices to have partially different content.
+ [ ] Fix `pre_delete` function to warn in case of deletion of non-indexed item.
+ [ ] Prevent overwrite of `_index` in `Search` instance from the manager if the `_index` variable is set to anything. This allows calls such as `Article.object.search.index('my_es_index').bungie_...` where the `index` call uses ES-dsl's function.
