### ISSUE TITLE
Add to PyPI

### ISSUE THREAD

**Issue by ChristopherRabotin** [Sparrho/bungiesearch#71]
Docs: https://packaging.python.org/en/latest/ .

**Comment by afrancis13** [comment]
Can you put this on PyPI? It would be awesome to make this easily usable in other Django projects.

Thanks!

**Comment by ChristopherRabotin** [comment]
I should have time to do that next week. In the meantime, you can add the following line to your `requirements.txt` file (it has the SHA-1 hash of the latest commit).
```
-e git+https://github.com/Sparrho/bungiesearch.git@767ea67101595d01b1b0df5c022245bb89de69ae#egg=bungiesearch
```

**Comment by afrancis13** [comment]
Yep, I got that. Thanks again, and looking forward to seeing it on PyPI.
