### ISSUE TITLE
Bug in signal processing - self.model is None

### ISSUE THREAD

**Issue by afrancis13** [Sparrho/bungiesearch#89]
```self.model``` is ```None``` here. It seems like this should not be the case, and may have slipped through the cracks. I'm going to try to make amends to this - Django seems to set ```self.model``` to ```None``` by default.

```
/Users/betterworks/bungiesearch/tests/core/models.py(5)<module>()

      3 

      4 

----> 5 class Article(models.Model):

      6     title = models.TextField(db_index=True)

      7     authors = models.TextField(blank=True)

/Users/betterworks/bungiesearch/tests/core/models.py(22)Article()

     20     popularity_index = models.IntegerField(default=0)

     21 

---> 22     objects = BungiesearchManager()

     23 

     24     class Meta:

> /Users/betterworks/bungiesearch/bungiesearch/managers.py(35)__init__()

     33         import ipdb; ipdb.set_trace()

     34         settings = Bungiesearch.BUNGIE

---> 35         if 'SIGNALS' in settings:

     36             self.signal_processor = get_signal_processor()

     37             self.signal_processor.setup(self.model)

ipdb> self.model

ipdb> type(self.model)

<type 'NoneType'>

```

**Comment by ChristopherRabotin** [comment]
The models are indeed set to `None` by default, but should be assigned after the initialization of the Django app. Where exactly did you encounter an error with a model set to `None`?

**Comment by afrancis13** [comment]
This is my mistake. I thought there was an issue because the return values were double what I was expecting, but I realized that the results were being returned from two separate indices. I was working with something else and playing around with the signals and seeing that self.model was None got me confused. Sorry!

**Comment by ChristopherRabotin** [comment]
No problem. For playing with several indices, what I usually do is have a search alias which selects a given index. For example, we have a long index and a short one, so we have two aliases, bungie_long and bungie_short which take zero arguments. They each select either the long or the short index. So when we retrieve info from a given model / doc type, we specify the index by doing ModelName objects bungie_long() (I can't add dots from my phone as it autocorrects things). Does that make sense? I can given you a full example if you want.
